index.html.md.erb
added details requested for "easily extensible"
=> First pass

installing-with-azure.html.md.erb
Added a note to validate the state database exists to
prevent confusion around the script "creating the db"
=> Added a Note to Validate the db exists

index.html.md.erb, release-notes.html.md.erb
[#177652860](https://www.pivotaltracker.com/story/show/177652860)
=> Retrospective release notes for v1.1.8

upgrading.html.md.erb
[#178223703](https://www.pivotaltracker.com/story/show/178223703)
=> Updates to upgrading page

release-notes.html.md.erb
[#178223703](https://www.pivotaltracker.com/story/show/178223703)
=> Add draft of known issue

release-notes.html.md.erb
[#178408788](https://www.pivotaltracker.com/story/show/178408788)
Co-authored-by: Marcela Campo <mcampo@pivotal.io>
=> updated release notes for 1.1.9

reference.html.md.erb
[#179001417](https://www.pivotaltracker.com/story/show/179001417)
=> Update docs for Azure mssql service

installing-with-azure.html.md.erb, reference.html.md.erb
[#179158078](https://www.pivotaltracker.com/story/show/179158078)
- Which other branches should this be merged with (if any)?
None
=> Update docs for Azure MSSQL DB service

azure-mssql-fog-subsume.html.md.erb, azure-mssql-subsume.html.md.erb
As we have improved the subsume testing, we noted that there is an
important step missing from the subsume documentation. This adds that
step.
[#179315094](https://www.pivotaltracker.com/story/show/179315094)
- 1.1
- master
=> docs: improve instructions for subsume

installing-with-azure.html.md.erb
[#179622297](https://www.pivotaltracker.com/story/show/179622297)
master
=> Add documentation about enabling encryption

index.html.md.erb, release-notes.html.md.erb
[#179749626](https://www.pivotaltracker.com/story/show/179749626)
none
=> Update release notes for 1.2.0 release

azure-mssql-fog-subsume.html.md.erb, azure-mssql-subsume.html.md.erb, reference.html.md.erb
[#179298527](https://www.pivotaltracker.com/story/show/179298527)
=> Add more options for setting the preconfigured servers

release-notes.html.md.erb
[#180082672](https://www.pivotaltracker.com/story/show/180082672)
=> Add DB known issue

release-notes.html.md.erb
=> Add release notes for 1.2.1

reference.html.md.erb
=> Add new properties for csb-azure-mssql-failover-group

reference.html.md.erb, release-notes.html.md.erb
These are release notes to be available for whenever we do the next release
master
=> Add release notes for mini plans

reference.html.md.erb
Adds:
- clarification on changing SKU
- docs for Resource Group
- docs for CosmosDB
- 1.3
=> Azure updates

reference.html.md.erb
Hi Docs! 👋
Adding documentation for the Azure MySql service. 
**Branches** Master & 1.2
Many thanks
James
=> Azure mysql

reference.html.md.erb
Hi Docs 👋
We are going through the Azure CSB and documenting the existing services. 
**Branches**: Master, 1.2
Please could this be merged and rebased if any other services have been merged since this PR? 
Many thanks
James
=> docs: add Azure Eventhub

reference.html.md.erb
Hi Docs! 👋
Thanks for dealing with all these recent PRs. 
**Branches:** Master & 1.2
Please could this be merged and rebased if there have been any other changes? 
Many thanks
James
=> docs: add azure mongob documentation

reference.html.md.erb
Hi Docs 👋
We have documented the Redis offering - this will be the last offering.
**Branches:** Master & 1.2
Please can this be merged and rebased against any other changes. 
Many thanks
James
=> docs: add azure Redis offering

installing-with-azure.html.md.erb, reference.html.md.erb
Hi Docs 🥇 
The next release of csb-azure-tile exposes the service mssql-server. This PR simply adds the fields which must be set if a user creates a plan in the tile. Previously they could only create a plan directly with the CF CLI. 
**Branches**: Master
Many thanks
James
=> Amend mssql server

installing-with-azure.html.md.erb, reference.html.md.erb
Hi Docs 👋
Small amend to the resource groups section to specify plan values which must be added when adding a new plan. 
**Branches**: master
Many thanks
James
=> Azure resource groups

installing-with-azure.html.md.erb
Hi Docs 👋
Just a little update to alert users to some functionality which is not intuitive.
Currently all update parameters must be supplied for each update. Incremental updates will lead to previously updated parameters reverting to default.
[#178213626](https://www.pivotaltracker.com/story/show/178213626)
**Branches** Master & 1.2
Many thanks
James
=> docs: add example on how to update SI

release-notes.html.md.erb
Hi Docs  👋 
Here are the release notes for 1.2 - we're targeting a release date of 2021-12-16.
Many thanks
CC @blgm
=> azure-tile: add release notes 1.2.2

installing-with-azure.html.md.erb, reference/azure-cosmosdb-mongo.html.md.erb, reference/azure-cosmosdb-sql.html.md.erb, reference/azure-eventhub.html.md.erb, reference/azure-mssql-db.html.md.erb, reference/azure-mssql-fog-preconfig.html.md.erb, reference/azure-mssql-fog-runner.html.md.erb, reference/azure-mssql-fog.html.md.erb, reference/azure-mssql-server.html.md.erb, reference/azure-mssql.html.md.erb, reference/azure-mysql.html.md.erb, reference/azure-postgresql.html.md.erb, reference/azure-redis.html.md.erb, reference/azure-resource-group.html.md.erb, reference/azure-storage-account.html.md.erb
[#180779926](https://www.pivotaltracker.com/story/show/180779926)
master
1.2
=> Update plan configs and params

azure-mssql-subsume.html.md.erb
=> Remove server-name from subsume params

index.html.md.erb, release-notes.html.md.erb
These are the release notes for the upcoming patch release.
=> add release notes for 1.2.3 and update product snapshot

reference/azure-postgresql.html.md.erb
[#181266428](https://www.pivotaltracker.com/story/show/181266428)
- 1.2
- 1.1
- 1.0
This should also be copied to the AWS and GCP docs, and I will submit subsequent PRs for that. But I'm going to wait for any editing on this one first.
=> PostgreSQL: note about persistence of user

index.html.md.erb, installing-with-azure.html.md.erb
=> Tidy up some links and add notes

release-notes.html.md.erb
- none
Target date for release 14 April (pending OSL)
=> docs: release notes for 1.2.4

installing-with-azure.html.md.erb
[#181848961](https://www.pivotaltracker.com/story/show/181848961)
Which other branches should this be merged with (if any)? Please merge to 1.2 branch too.
=> clarify state database setup

release-notes.html.md.erb
- Note that I created the `1.3` branch
- Note that this refers to docs created in PR #71
=> Release notes for v1.3.0

index.html.md.erb, release-notes.html.md.erb
Which other branches should this be merged with (if any)? none
=> Release notes 1.3.1

release-notes.html.md.erb
Which other branches should this be merged with (if any)? 1.3 only
=> remove unneeded config documentation

release-notes.html.md.erb
=> Add some missed release notes for latest release.

reference/azure-redis.html.md.erb, release-notes.html.md.erb, upgrading.html.md.erb
=> Add release notes for redis version

upgrading.html.md.erb
=> Redis: fix a format error

reference/azure-redis.html.md.erb, release-notes.html.md.erb, upgrading.html.md.erb
=> Document Redis plan deprecation

reference/azure-cosmosdb-mongo.html.md.erb, reference/azure-cosmosdb-sql.html.md.erb, release-notes.html.md.erb
=> Add cosmos db sql release notes

upgrading.html.md.erb
=> Redis: fix markup

release-notes.html.md.erb
[#184161683](https://www.pivotaltracker.com/story/show/184161683)
=> release notes for 1.4.1

release-notes.html.md.erb
[#184460134](https://www.pivotaltracker.com/story/show/184460134)
- none
=> release notes: redis upgrade fix

reference/azure-cosmosdb-sql.html.md.erb, reference/azure-eventhub.html.md.erb, reference/azure-mssql-fog-preconfig.html.md.erb, reference/azure-mssql-fog.html.md.erb, reference/azure-mssql.html.md.erb, reference/azure-postgresql.html.md.erb
[#184613881](https://www.pivotaltracker.com/story/show/184613881)
- 1.4
- 1.3
=> fix some historic mismatches with the implementation

reference/azure-cosmosdb-sql.html.md.erb, reference/azure-mssql-fog-runner.html.md.erb
[#184613881](https://www.pivotaltracker.com/story/show/184613881)
- 1.4
- 1.3
=> add operation to failover runner props for consistency

reference/azure-mssql-db.html.md.erb, reference/azure-mssql-fog-preconfig.html.md.erb, reference/azure-mssql-fog.html.md.erb, reference/azure-mssql-server.html.md.erb, reference/azure-mssql.html.md.erb, reference/azure-postgresql.html.md.erb
[#184710879](https://www.pivotaltracker.com/story/show/184710879)
- 1.4
- 1.3
=> fix some more default values

reference/azure-cosmosdb-mongo.html.md.erb, reference/azure-cosmosdb-sql.html.md.erb, reference/azure-eventhub.html.md.erb, reference/azure-mssql-db.html.md.erb, reference/azure-mssql-fog-preconfig.html.md.erb, reference/azure-mssql-fog.html.md.erb, reference/azure-mssql-server.html.md.erb, reference/azure-mssql.html.md.erb, reference/azure-mysql.html.md.erb, reference/azure-postgresql.html.md.erb, reference/azure-redis.html.md.erb, reference/azure-resource-group.html.md.erb, reference/azure-storage-account.html.md.erb
Which other branches should this be merged with (if any)? 1.2, 1.3, 1.4
=> document correct parameters to set marketplance information

index.html.md.erb, reference/azure-mssql-db.html.md.erb, reference/azure-mssql-fog-preconfig.html.md.erb
This is for the upcoming 1.4.3 release
=> add new long term retention parameters

reference/azure-mssql-db.html.md.erb, reference/azure-mssql-fog-preconfig.html.md.erb
=> Add long term retention fields

release-notes.html.md.erb
[#183376494](https://www.pivotaltracker.com/story/show/183376494)
None
=> Fixed error `Argument list too long` when starting the application

upgrading.html.md.erb
=> upgrading: remove instructions for previous minor

release-notes.html.md.erb
=> Long-term backup retention exposed

upgrading.html.md.erb
=> upgrade: simplify upgrading instructions

upgrading.html.md.erb
=> upgrade: improve upgrade instructions

index.html.md.erb, release-notes.html.md.erb
=> Tile depends now on Jammy stemcell

reference/azure-mssql-db.html.md.erb, reference/azure-mssql.html.md.erb, release-notes.html.md.erb
[#185100152](https://www.pivotaltracker.com/story/show/185100152)
None
=> MSSQL: add fixed issue about unbinding operation

release-notes.html.md.erb, upgrading.html.md.erb
=> Check instances are up to date before upgrading.

release-notes.html.md.erb
=> Add stack selection fixed issue

release-notes.html.md.erb
=> Delete database rows

release-notes.html.md.erb
=> upgrade terraform version

release-notes.html.md.erb
[#186654449](https://www.pivotaltracker.com/story/show/186654449)
- none
=> docs: known issue with change to Jammy stemcell

release-notes.html.md.erb
=> We now fail if there are upgrade errors

config/toc.md, managing_orphaned_service_instances.html.md.erb
This is an edited copy of the file from AWS: https://github.com/pivotal-cf/docs-csb-aws/blob/main/managing_orphaned_service_instances.html.md.erb
[#186663906](https://www.pivotaltracker.com/story/show/186663906)
- main
- 1.5
- 1.4
- 1.3
=> doc: managing instances from deactivated plans

upgrading.html.md.erb
=> Pre upgrade section

release-notes.html.md.erb
=> document new installation safety checks

reference/azure-cosmosdb-mongo.html.md.erb, release-notes.html.md.erb, troubleshooting.html.md.erb
[#186981808](https://www.pivotaltracker.com/story/show/186981808)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-azure/pull/677
- https://github.com/cloudfoundry/csb-brokerpak-azure/pull/676
=> feat: support custom indexes and unique indexes for mongodb

reference/azure-cosmosdb-mongo.html.md.erb
[#186981808](https://www.pivotaltracker.com/story/show/186981808)
None
=> fix: mongodb unique index

release-notes.html.md.erb, upgrading.html.md.erb
[#187362878](https://www.pivotaltracker.com/story/show/187362878)
None
=> chore: release notes - add missing items

release-notes.html.md.erb
=> chore: release notes for patch 1.8.1

release-notes.html.md.erb
=> Add marking in-progress operations as failed issue

config/toc.md, custom-plans.html.md.erb, reference/azure-cosmosdb-mongo.html.md.erb, reference/azure-cosmosdb-sql.html.md.erb, reference/azure-eventhub.html.md.erb, reference/azure-mssql-db.html.md.erb, reference/azure-mssql-fog-preconfig.html.md.erb, reference/azure-mssql-fog-runner.html.md.erb, reference/azure-mssql-fog.html.md.erb, reference/azure-mssql-server.html.md.erb, reference/azure-mssql.html.md.erb, reference/azure-mysql.html.md.erb, reference/azure-postgresql.html.md.erb, reference/azure-redis.html.md.erb, reference/azure-resource-group.html.md.erb, reference/azure-storage-account.html.md.erb
=> docs: add recommendation to use custom plans

reference/azure-mysql.html.md.erb, reference/azure-postgresql.html.md.erb
=> Add retirement notice to MySQL and PostgreSQL

reference/azure-postgresql-flexible-server.html.md.erb, reference/index.html.md.erb, release-notes.html.md.erb
=> Release notes and ref docs for PostgreSQL Flexible Server

reference/azure-postgresql-flexible-server.html.md.erb
=> Add property skip_provider_registration for flexible server

reference/azure-postgresql-flexible-server.html.md.erb
=> Update postgres flexible server property values

config/toc.md, reference/azure-postgresql-flexible-server.html.md.erb, release-notes.html.md.erb
[#187641295](https://www.pivotaltracker.com/story/show/187641295)
None
=> PostgreSQL Flexible server: small improvements

release-notes.html.md.erb
=> Updated release notest with tofu upgrade

release-notes.html.md.erb
=> Update release notes with latest tofu version
